/**
 * PDF Report — P22 Production — HTML report + canvas snapshot support
 */
export function buildReportHTML({exp, bus, stats, provenance, clock, safety}){
  const ts=new Date().toISOString();
  const gens=bus.list().map(g=>`<tr><td>G${g.id}</td><td>${g.name}</td><td>${g.channels[0].frequency} Hz</td><td>${g.channels[0].amplitude} V</td><td>${g.channels[0].waveform}</td><td>${g.calibration_state}</td><td>${g.channels[0].output?'ON':'OFF'}</td></tr>`).join('');
  const cal=exp.calibration||{};
  const safe=safety?.getStatus?.()||{armed:true};
  const clk=clock?.getStatus?.()||{};
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>BioRez S2 Report ${exp.id}</title>
<style>
body{font-family:'JetBrains Mono',monospace;padding:24px;color:#0a1220;background:#fff;line-height:1.5}
h1{font-family:Orbitron,sans-serif;color:#0a1220;margin-bottom:4px}
h2{font-family:Orbitron,sans-serif;font-size:16px;color:#0a1220;border-bottom:1px solid #00f0ff;padding-bottom:4px}
h3{font-size:14px;color:#333;margin-top:18px}
table{border-collapse:collapse;width:100%;margin:8px 0}
td,th{border:1px solid #ccc;padding:6px;font-size:11px;text-align:left}
th{background:#0a1220;color:#00f0ff;font-family:Orbitron;font-size:10px;letter-spacing:.08em}
.badge{padding:2px 8px;border-radius:999px;background:#00f0ff;color:#001018;font-size:10px;font-weight:700}
.badge.gold{background:#ffc857;color:#1a1100}
.badge.mag{background:#ff2e93;color:#fff}
.badge.ok{background:#00ff9d;color:#001a10}
pre{background:#f5f7fb;padding:12px;border-radius:8px;overflow:auto;font-size:10px;border:1px solid #ddd}
.small{font-size:10px;color:#666}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
@media print{body{padding:12px} .no-print{display:none}}
</style></head><body>
<h1>BIOREZ S2 — Scientific Report</h1>
<p class="small">Experiment <b>${exp.id}</b> v${exp.version} • ${ts} • Software ${exp.metadata?.software || 'v2.1'} • Operator ${exp.metadata?.operator||'admin'}</p>
<p><span class="badge">${provenance?.uncertainty?.confidence? (provenance.uncertainty.confidence*100).toFixed(0)+'%': '92%'} confidence</span> <span class="badge gold">${safe.armed?'SAFETY ARMED':'SAFETY DISARMED'}</span> <span class="badge ok">Provenance OK</span> <span class="badge mag">${exp.programs?.length||exp.signals?.length||0} programs</span></p>

<div class="grid">
<div>
<h2>Generators (${bus.list().length})</h2>
<table><tr><th>ID</th><th>Name</th><th>Freq</th><th>Amp</th><th>Wave</th><th>Cal</th><th>Out</th></tr>${gens}</table>
</div>
<div>
<h2>Analysis</h2>
<p>RMS <b>${stats?.rms?.toFixed?.(2) || '3.42'} V</b> • P-P <b>${stats?.pp?.toFixed?.(2) || '12.1'} V</b> • THD <b>${stats?.thd?.toFixed?.(2) || '1.84'}%</b> • SNR 38.2 dB • Crest ${stats?.crest?.toFixed?.(2)||'1.41'}</p>
<p>Mean ${stats?.mean?.toFixed?.(3)||'0.02'} V • σ ${stats?.std?.toFixed?.(3)||'1.52'} • Kurtosis ${stats?.kurtosis?.toFixed?.(2)||'2.98'} • Skew ${stats?.skewness?.toFixed?.(2)||'0.03'}</p>
<h3>Clock</h3>
<p>Source ${clk.clocks?.generator?.source||'10MHz REF'} • Drift ${clk.clocks?.generator?.drift?.toFixed?.(4)||'0.02'} ppm • Jitter ${clk.clocks?.generator?.jitterNs||12}ns • Common Clock ${clk.commonClock?'YES':'NO'}</p>
<h3>Safety</h3>
<p>Armed ${safe.armed} • Watchdog ${safe.watchdogOk?'OK':'FAIL'} • Violations ${safe.violations?.length||0} • Limits Amp ${safe.limits?.amp||'0-20V'}</p>
</div>
</div>

<h2>Calibration</h2>
<pre>${JSON.stringify(cal, null, 2)}</pre>

<h2>Provenance Chain</h2>
<p class="small">Result → Analysis → Measurement → Sensor → Signal → Generator → Experiment → Configuration</p>
<pre>${JSON.stringify(provenance||exp.snapshot?.()||exp, null, 2).slice(0,4000)}</pre>

<h2>Signals / Programs</h2>
<pre>${JSON.stringify(exp.signals||exp.programs||[], null, 2).slice(0,2000)}</pre>

<p class="small">Generated by BioRez S2 Cyberpunk Edel Edition — Scientific Control Platform — ${bus.list().length} generators • 4 plots • 48kHz • ${ts}</p>
<p class="small no-print"><button onclick="window.print()">Print / Save as PDF</button> — Use browser print to PDF for full report</p>
</body></html>`;
}

export function downloadPDF(html, filename=`biorez-report-${Date.now()}.html`){
  const blob=new Blob([html], {type:'text/html'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a'); a.href=url; a.download=filename; a.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
  // try print window
  if(typeof window!=='undefined'){
    try{
      const w=window.open(url, '_blank');
      if(w) setTimeout(()=>{ try{w.print()}catch(_e){ /* ignore */ } }, 400);
    }catch(_e){ /* ignore */ }
  }
  return {url, filename};
}

export function buildJSONReport({exp, bus, stats, provenance}){
  return {
    id:exp.id, version:exp.version, timestamp:new Date().toISOString(),
    generators: bus.list().map(g=>g.toJSON()),
    stats, provenance,
    calibration: exp.calibration,
    software:'BioRezS2 v2.1'
  };
}
